from django.apps import AppConfig


class FollowersConfig(AppConfig):
    """An application configuration class automatically generated by Django."""

    default_auto_field = 'django.db.models.BigAutoField'
    name = 'followers'
    verbose_name = 'Подписчики'
