# Generated by Django 3.2.16 on 2024-05-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_add_ingredient_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='Unique ingredient',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique ingredient'),
        ),
    ]
