from django.apps import AppConfig


class ApiConfig(AppConfig):
    """An application configuration class automatically generated by Django."""

    default_auto_field = 'django.db.models.BigAutoField'
    name = 'api'
