version: '3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
#    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
#    container_name: foodgram_backend
    image: kaleontyev/foodgram_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media


  frontend:
#    container_name: foodgram_frontend
    image: kaleontyev/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    env_file: .env
    volumes:
      - static:/frontend_static

  gateway:
#    container_name: foodgram_gateway
    image: kaleontyev/foodgram_gateway
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - media:/media