version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
#    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
#    container_name: backend
    image: kaleontyev/foodgram_backend
    env_file: .env
    command: cp -r /app/collected_static/. /backend_static/static/
    depends_on:
      - db
      - frontend
    volumes:
      - static:/backend_static/
      - media:/app/media/

  frontend:
#    container_name: frontend
    image: kaleontyev/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  gateway:
#    container_name: gateway
    image: kaleontyev/foodgram_gateway
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - media:/media/
