volumes:
  kkalogram_pg_data:
  kkalogram_static:
  kkalogram_media:

services:
  db:
    container_name: kkalogram_db
    image: postgres:13.10
    env_file: .env
    volumes:
      - kkalogram_pg_data:/var/lib/postgresql/data

  frontend:
    container_name: kkalogram_frontend
    image: kaleontyev/kkalogram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - kkalogram_static:/frontend_static

  backend:
    container_name: kkalogram_backend
    image: kaleontyev/kkalogram_backend
    env_file: .env
    depends_on:
      - db
      - frontend
    volumes:
      - kkalogram_static:/backend_static
      - kkalogram_media:/media

  gateway:
    container_name: kkalogram_gateway
    image: kaleontyev/kkalogram_gateway
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80
    volumes:
      - kkalogram_static:/staticfiles
      - kkalogram_media:/media
