version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
#    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
#    container_name: foodgram_backend
    build: ./backend/
    env_file: .env
    command: cp -r /app/collected_static/. /backend_static/static/
    depends_on:
      - db
    volumes:
      - static:/backend_static/

  frontend:
#    container_name: foodgram_frontend
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  gateway:
#    container_name: gateway
    build: ./gateway/
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - media:/media/