version: '3'

volumes:
  pg_data:
  static:


services:
  db:
#    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
#    container_name: foodgram_backend
    build: ./backend/
    depends_on:
      - db
    env_file: .env
    volumes:
      - static:/backend_static


  frontend:
#    container_name: foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    build: ./frontend/
    env_file: .env
    volumes:
      - static:/frontend_static

  gateway:
#    container_name: gateway
    build: ./gateway/
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/