from django.apps import AppConfig


class RecipesConfig(AppConfig):
    """An application configuration class automatically generated by Django."""

    default_auto_field = 'django.db.models.BigAutoField'
    name = 'recipes'
    verbose_name = 'Список рецептов'
