version: '3.3'

volumes:
  frontend:
  media_dir:
  pg_data:
  static_dir:


services:

  frontend:
    container_name: foodgram_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/

  db:
    container_name: db
    env_file: ./.env
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    depends_on:
      - db

  backend:
    container_name: foodgram_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ../.env
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/

  nginx:
    container_name: gateway
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend
