from django.apps import AppConfig


class IngredientsConfig(AppConfig):
    """An application configuration class automatically generated by Django."""

    default_auto_field = 'django.db.models.BigAutoField'
    name = 'ingredients'
    verbose_name = 'Список ингредиентов'
