from django.apps import AppConfig


class TagsConfig(AppConfig):
    """An application configuration class automatically generated by Django."""

    default_auto_field = 'django.db.models.BigAutoField'
    name = 'tags'
    verbose_name = 'Список тегов'
